### PR TITLE
Removed the firewall profile - 

### PR DESCRIPTION
**Pull request by pagbabian-splunk**
#### Description of changes:
Removed the firewall profile from 1.1-dev; the security_control profile supports firewall now.

### CODE REVIEW

**Comment by floydtree** [comment]
Looks like the server is failing to run with this change. https://github.com/ocsf/ocsf-schema/pull/889/checks

**Review by floydtree — CHANGES_REQUESTED** [review]
Looks like the server runs are failing, will need to remove other references to this profile

**Comment by pagbabian-splunk** [comment]
Crap, sorry - missed that.  Let me fix.

**Review by floydtree — APPROVED** [review]

**Review by adplotzk — APPROVED** [review]
Removing of firewall is expected and approved.

**Review by Aniak5 — APPROVED** [review]
LGTM!

**Pull request merged**
