### PR TITLE
#884 Add firewall, router, switch, hub to endpoint types.

### PR DESCRIPTION
**Pull request by mikeradka**
#### Description of changes: Adds firewall, router, switch, hub to endpoint types. We want to get this in before 1.1.

image

### CODE REVIEW

**Review by floydtree — APPROVED** [review]

**Review by Aniak5 — APPROVED** [review]
Good call on adding these!

**Comment by pagbabian-splunk** [comment]
Should we have descriptions for Firewall, Switch, and Hub?

**Comment by mikeradka** [comment]
> Should we have descriptions for Firewall, Switch, and Hub?

Good thinking. I added descriptions with links.

**Comment by mikeradka** [comment]
I removed UTM - per [Cisco](https://www.cisco.com/c/en/us/products/security/firewalls/what-is-a-firewall.html), a UTM is a specific type of firewall (along with 6 or 7 others). I think we should keep it to `firewall`, and talk to @pladam about maybe adding a way to specify the firewall type in the profile he is working.

**Comment by pagbabian-splunk** [comment]
We should add the different firewall types (e.g. NGFW, UTM) to the `Security Control` profile, we merged in the `Firewall` profile into that profile, adding the `firewall_rule` object, so it makes most sense there.

**Review by pagbabian-splunk — APPROVED** [review]

**Comment by Aniak5** [comment]
Looks great! I like how you added the links for further detail on each device type!
image

**Review by Aniak5 — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Pull request merged**
