### PR TITLE
update dns activity

### PR DESCRIPTION
**Pull request by Aniak5**
Signed-off-by: Ania Kacewicz <ania.kacewicz@gmail.com>
#350 
image

### CODE REVIEW

**Comment by paveljos** [comment]
We have plans on utilizing "Reset" due to firewall activity: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-query-logs-format.html

I don't think it's a far cry to say that we can imagine certain records giving traffic reports as well, although I don't have a use case for that right now. I'd recommend leaving them for the time.

**Comment by rroupski** [comment]
Not needed

**Comment by mr-splunk** [comment]
I know that Query and Response logs can easily be produced, but do we know if Reset logs are produced?

'Traffic' i'm unfamiliar with, unless this alludes to pcap data of DNS traffic.

**Comment by mr-splunk** [comment]
Looking at this once more, it looks like the change just gets rid of 'unresolved' and changes the tense to present. That looks good to me.

**Review by mr-splunk — APPROVED** [review]

**Pull request merged**
