### PR TITLE
change the duration attribute to long_t

### PR DESCRIPTION
**Pull request by jasonbreimer**
This should be long_t if we keep this as an attribute.

#### Description of changes:
Several discussion's regarding the duration attribute. I believe this change is necessary if we keep this as an attribute.

There was some discussion of making this a new object.

### CODE REVIEW

**Comment by jasonbreimer** [comment]
This change passes local elixir testing.

However this PR is in draft as its not clear there's agreement.

**Comment by query-jeremy** [comment]
This is _technically_ a breaking change, but nearly all encodings (& data stores, heap managers, etc.) I can think of can roll with `int -> long` without problem. Might be better to allow `int -> long` in our breaking change rules.

**Comment by jasonbreimer** [comment]
To Jeremy's point I think this is technically a breaking change but its a bug fix so..... I think we can proceed? Marking as ready for review.

**Comment by mlmitch** [comment]
I like it.

**Review by Aniak5 — APPROVED** [review]

**Comment by Aniak5** [comment]
Should we also make `handshake_dur` and `lease_dur` a long type too?

**Review by zschmerber — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Pull request merged**
