### PR TITLE
#470 Promote Splunk's Network File Activity event class to OCSF core

### PR DESCRIPTION
**Pull request by mr-splunk**
image

### CODE REVIEW

**Review by rroupski — APPROVED** [review]

**Comment by floydtree** [comment]
Based on the description of `user` and `session` fields, looks like they are meant to convey information about the source of the activity on the file. 

Can we used the `actor` object instead? (actor contains user and session)
>The actor object describes details about the user/role/process that was the source of the activity.

By this change, we can make this class more consistent with other access/audit classes which report information about activities about a resource performed by a user. 

Curious to hear your thoughts.

**Comment by mr-splunk** [comment]
> 

At first glance, this might work. Nice suggestion, Rajas. Let me take a look at some examples in practice.

**Review by floydtree — APPROVED** [review]
Looks good.

**Review by rroupski — APPROVED** [review]

**Review by Aniak5 — APPROVED** [review]
LGTM!

**Pull request merged**
