### PR TITLE
Adding a new field in the vulnerability object.

### PR DESCRIPTION
**Pull request by floydtree**
Adding `fix_available` in the dictionary and the vulnerability object.
This is an implementation of https://github.com/ocsf/ocsf-schema/discussions/481.

Screen Shot 2023-03-07 at 9 50 04 AM

Signed-off-by: Rajas [rajaspa@amazon.com](mailto:rajaspa@amazon.com)

### CODE REVIEW

**Review by Aniak5 — APPROVED** [review]
LGTM

**Review by irakledibm — APPROVED** [review]
Reviewed

**Comment by mr-splunk** [comment]
Only very nitpicky thing, the caption `Fix availability` - I think for captions we usually capitalize each word of the caption. Just to make it more 'polished'. Otherwise, looks good to me :)

**Review by mr-splunk — CHANGES_REQUESTED** [review]
Only very nitpicky thing, the caption `Fix availability` - I think for captions we usually capitalize each word of the caption. Just to make it more 'polished', could it instead read `Fix Availability`? Otherwise, looks good to me :)

**Review by mr-splunk — APPROVED** [review]

**Review by irakledibm — APPROVED** [review]

**Pull request merged**
