### PR TITLE
Update description for user_inventory.json

### PR DESCRIPTION
**Pull request by jasonbreimer**
Fix description. Looks like a portion of the description text was removed at some point.

I have restored the original text from history.

#### Related Issue: 
Issue #933 

#### Description of changes:
restored the description text.

### CODE REVIEW

**Comment by jasonbreimer** [comment]
passed local elixir testing.

**Comment by floydtree** [comment]
Hey Jason, it looks like @pagbabian-splunk covered this change in https://github.com/ocsf/ocsf-schema/pull/942.

**Comment by jasonbreimer** [comment]
Looks like Paul beat me too this! Closing this case for Paul's:https://github.com/ocsf/ocsf-schema/pull/942

**Comment by jasonbreimer** [comment]
See https://github.com/ocsf/ocsf-schema/pull/942

**Pull request closed without merging**
