### PR TITLE
Use list auto-numbering in unreleased section of change-log; reduces merge conflicts 

### PR DESCRIPTION
**Pull request by antchan2**
#### Related Issue: 

N/A

#### Description of changes:

Open pull requests often include a corresponding change in CHANGELOG.md. When multiple pull requests are active, each change assumes they are next to be merged and so lists its own change as the next entry in a numbered list. This is a problem when multiple pull requests are scheduled to be merged in a similar timeframe. When a different change is merged first, the author of open PRs must update the change-log entry in their own pull request with a new number and wait again. The following commit illustrates this change-log shuffle:

https://github.com/ocsf/ocsf-schema/pull/1196/commits/90bebba82dd49b6843c749950739cb472b24101d

This pull request proposes using list auto-numbering for the "Unreleased" section of the change-log file to eliminate this process inefficiency. If there is a desire to show the final numbered list in the raw Markdown, this can be done "all at once" when the unreleased changes are bundled in a release.

### CODE REVIEW

**Review by floydtree — APPROVED** [review]

**Review by zschmerber — DISMISSED** [review]
Love this!

**Review by jonrau-at-queryai — APPROVED** [review]

**Comment by antchan2** [comment]
Sorry about a few copy-and-paste issues. Fixed in f2f1e09 and 7685ebf.

**Comment by davemcatcisco** [comment]
Very cool!

**Review by floydtree — APPROVED** [review]

**Review by Aniak5 — DISMISSED** [review]
Good idea!

**Review by davemcatcisco — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Review by Aniak5 — APPROVED** [review]

**Pull request merged**
