### PR TITLE
New Discovery software inventory class

### PR DESCRIPTION
**Pull request by jasonbreimer**
New Discovery class for software inventory data captured via a log or collection process. 

This new class is a companion and mirrors the Discovery class Device Inventory Info 5001.

#### Description of changes:
1. This class models locally or scanned sourced software details.
2. Primary using device, software package, and product objects.
3. The Software Package object is to be used for Device specific software details.
4. The Product object (optional) can be used to capture additional software product details as part of a vendor's software catalog.

### CODE REVIEW

**Comment by mikeradka** [comment]
Hi @jasonbreimer, take a look at the validation task, it looks like something may have failed against the metaschema.

**Comment by jasonbreimer** [comment]
Thanks @mikeradka!

**Review by floydtree — APPROVED** [review]

**Review by floydtree — CHANGES_REQUESTED** [review]
Looks good! Just a small thing, can you add a Changelog entry for this?

**Comment by mikeradka** [comment]
@jasonbreimer Please make sure to update CHANGELOG.md for this one

**Review by mikeradka — APPROVED** [review]

**Comment by jasonbreimer** [comment]
> Looks good! Just a small thing, can you add a Changelog entry for this?

Done! thank you!

**Review by floydtree — APPROVED** [review]

**Review by zschmerber — APPROVED** [review]
Nice work we can now capture CIS controls 1 & 2.!

**Pull request merged**
