### PR TITLE
Rename IP Port caption as Port

### PR DESCRIPTION
**Pull request by rroupski**

### CODE REVIEW

**Review by floydtree — CHANGES_REQUESTED** [review]
I think it will be more appropriate if the description reads - `The TCP/IP port number.....`

(TCP/IP is synonymous to the **TCP/IP protocol stack**)

**Review by Aniak5 — APPROVED** [review]

**Comment by rroupski** [comment]
The port can be used by other protocols in addition to TCP, for example UDP and ICMP.

**Review by rroupski — COMMENTED** [review]
The port can be used by other protocols such as UDP.

**Comment by floydtree** [comment]
Correct about UDP. (ICMP doesn't have a concept of ports btw, it's a network layer protocol). I am referring to the TCP/IP stack as a blank term and not the specific protocols. The Internet protocol suite is commonly known as TCP/IP.

There isn't much clarity on the naming via RFCs either. So, if you think TCP/IP is misleading in the description, IP port might just be fine.

**Pull request merged**
