### PR TITLE
Issue 347- Update DHCP event class

### PR DESCRIPTION
**Pull request by Aniak5**
#347 

Following [this](https://docs.zeek.org/en/master/scripts/base/protocols/dhcp/main.zeek.html) comprehensive Zeek DHCP log

### CODE REVIEW

**Review by mr-splunk — COMMENTED** [review]
I want to take a deeper look at this. src_endpoint at a glance looks good, but not sure how dst_endpoint differs from the logging device, which i've usually seen as the dhcp server itself.

I can look at this through the lens of Infoblox DHCP events, is there a way we could get events from other DHCP services, like Linux DHCPD?

**Comment by Aniak5** [comment]
@mr-splunk [here](https://docs.infoblox.com/space/BloxOneThreatDefense/35472716/DHCP+Message+Mapping) is a link for the Infoblox DHCP mapping. In general, within the `network` activity we have used the `src_endpoint` to indicate the client and the `dst_endpoint` to indicate the server so we would be consistent with this here.

Let me look into this!

**Comment by mr-splunk** [comment]
> @mr-splunk [here](https://docs.infoblox.com/space/BloxOneThreatDefense/35472716/DHCP+Message+Mapping) is a link for the Infoblox DHCP mapping. In general, within the `network` activity we have used the `src_endpoint` to indicate the client and the `dst_endpoint` to indicate the server so we would be consistent with this here.
> 
> Let me look into this!

Hi Ania, thanks for looking, I have not had the chance to revisit this very much recently. What I can share is some Infoblox sample logs from the "Infoblox NIOS" product, which are in syslog format and what Splunk supports:

1. Infoblox ACK sample:

`<30>Sep 13 10:10:46 192.168.2.1 dhcpd[13613]: DHCPACK on 192.168.1.120 to 00:50:56:44:55:66 (WORKSTATION1) via eth1 relay eth1 lease-duration 600 (RENEW) uid 01:00:50:56:44:55:66`

2. Infoblox  EXPIRE sample:

`<30>May 5 11:22:11 10.2.2.1 dhcpd[10005]: DHCPEXPIRE on 10.3.3.1 to 38:f9:d3:aa:bb:cc`

4. Infoblox RELEASE sample:

`<30>May 19 11:22:10 10.2.2.1 dhcpd[10006]: DHCPRELEASE of 10.3.3.2 from b8:80:4f:11:22:33 (WORKSTATION2) via eth2 (found) TransID ae3db75d uid 01:b8:80:4f:11:22:33`

Let me know if you'd like to sync on how those are currently mapped to OCSF.

**Comment by mr-splunk** [comment]
Is it possible to instead of 'assigned_ip' and 'requested_ip', just make them `server` and `client`? This is what it would look like:

`{
  "activity_id": 9,
  "category_uid": 4,
  "class_uid": 4004,
  "client": {
    "ip": "192.168.1.120",
    "mac": "00:50:56:13:60:56",
    "type_id": 0
  },
  "device": {
    "os": {
      "name": "Linux",
      "type_id": 200
    },
    "type_id": 1
  },
  "message": "DHCPEXPIRE on 192.168.1.120 to 00:50:56:13:60:56",
  "metadata": {
    "original_time": "Sep 28 04:45:33",
    "product": {
      "feature": {
        "name": "DHCP"
      },
      "name": "Infoblox NIOS",
      "vendor_name": "Infoblox"
    },
    "profiles": [
      "host"
    ],
    "uid": "3bbe3345-d7b3-48ae-959b-4bba7a0a2890",
    "version": "0.33.0"
  },
  "server": {
    "ip": "192.168.1.2"
  },
  "severity_id": 1,
  "time": 1669932867284,
  "unmapped": {
    "event_data": {
      "refEventName": "DHCPEXPIRE"
    },
    "facility": 3,
    "pid": "27785"
  }
}`

**Review by rroupski — APPROVED** [review]

**Review by mr-splunk — APPROVED** [review]
This is much more straightforward. Thank you for being patient throughout these conversations and making this change, Ania!

**Pull request merged**
