### PR TITLE
Software package object improvements

### PR DESCRIPTION
**Pull request by jasonbreimer**
Add two additional attributes for the Software Package object. In both instances the pre-existing attribute is used to uniquely identify the package. This can be useful when looking at Software Bill of Materials (SBOM) inventory data. 

#### Description of changes:
Add cpe_name attribute. Common Platform Enumeration CPE is used to uniquely identity software packages. 
Add hash attribute. A cryptographic hash is another common way to identify software packages.  

These changes pass local validation testing.

### CODE REVIEW

**Review by floydtree — COMMENTED** [review]
Looks good, just needs an entry in the changelog

**Comment by jasonbreimer** [comment]
Requested CHANGELOG addition has been made. Thank you!

**Review by mikeradka — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Review by Aniak5 — APPROVED** [review]
LGTM

**Comment by mikeradka** [comment]
@jasonbreimer it looks like we have the required approvals needed to get this pushed, but the latest changes from `main` have to be merged into this branch before merging this PR

**Pull request merged**
