### PR TITLE
Issue 689: Add type/type_id to endpoint object

### PR DESCRIPTION
**Pull request by Aniak5**
#### Description of changes:

- Moved device type enums to endpoint object 
- Updates device/network_endpoint objects to have specific type requirements/descriptions

image

### CODE REVIEW

**Review by mr-splunk — DISMISSED** [review]
LGTM

**Comment by mr-splunk** [comment]
Hi @Aniak5 , - Along the topic of Endpoint - saw a minor grammatical error in the description of the Endpoint observable in the observable object

`The endpoint object describes an entity that has name, uid, and IP address.`
should be
`The endpoint object describes an entity that has a name, uid, and IP address.`

Is this something you could add to this PR?

**Review by rroupski — CHANGES_REQUESTED** [review]
The `endpoint` object is not a private object, so we should rename the file as `endpoint.json`.

**Comment by Aniak5** [comment]
> Hi @Aniak5 , - Along the topic of Endpoint - saw a minor grammatical error in the description of the Endpoint observable in the observable object
> 
> `The endpoint object describes an entity that has name, uid, and IP address.` should be `The endpoint object describes an entity that has a name, uid, and IP address.`
> 
> Is this something you could add to this PR?

Yup definitely, good catch @mr-splunk!

**Review by mr-splunk — APPROVED** [review]

**Review by rroupski — APPROVED** [review]

**Review by floydtree — APPROVED** [review]

**Pull request merged**
