### PR TITLE
Email: Remove Duplicate Email UID

### PR DESCRIPTION
**Pull request by ablyler**
The email class contains the email_uid attribute and it is also in the included email trait

Signed-off-by: Andy Blyler <ablyler@barracuda.com>

### CODE REVIEW

**Comment by Aniak5** [comment]
It looks like your recent changes removing the `connection_uid` are not in this PR.

**Review by rroupski — APPROVED** [review]

**Review by Aniak5 — COMMENTED** [review]
The `connection_uid` lines 40-43 which were removed by [this PR ](https://github.com/ocsf/ocsf-schema/pull/410/files) are still showing up in the current PR. I think you likely just need to rebase off of/merge the most recent master branch.

**Comment by ablyler** [comment]
> The `connection_uid` lines 40-43 which were removed by [this PR ](https://github.com/ocsf/ocsf-schema/pull/410/files) are still showing up in the current PR. I think you likely just need to rebase off of/merge the most recent master branch.

Should be fixed up now.

**Review by Aniak5 — APPROVED** [review]
LGTM!

**Pull request merged**
