### PR TITLE
Added job attribute to Evidence Artifacts object.

### PR DESCRIPTION
**Pull request by davemcatcisco**
#### Related Issue: 

[#1124](https://github.com/ocsf/ocsf-schema/issues/1124)

#### Description of changes:

- Added the pre-existing `job` attribute to the `Evidence Artifacts` object.
- Adjusted the `at_least_one` constraint in the object to include `job`.

Note that this approach is the same as that taken to fix other gaps in the `Evidence Artifacts` object, e.g. PR #1078.

### CODE REVIEW

**Review by floydtree — APPROVED** [review]

**Review by mikeradka — DISMISSED** [review]
This looks good to me

**Comment by davemcatcisco** [comment]
@mikeradka and @floydtree - I had to resolve conflicts that had arisen and this dismissed your previous reviews. Can you please re-approve.

@pagbabian-splunk, @Aniak5, and @zschmerber - I need one more approver. This PR has been open for several weeks waiting for another approver. I'd be most grateful if one of you could do the needful.

**Review by mikeradka — APPROVED** [review]

**Review by Aniak5 — COMMENTED** [review]
LGTM!

**Review by Aniak5 — APPROVED** [review]

**Comment by davemcatcisco** [comment]
Thanks, all.

**Pull request merged**
