### PR TITLE
Adding consistency in boolean attribute naming

### PR DESCRIPTION
**Pull request by floydtree**
#### Description of changes:
1. Adding a new attribute `is_fix_available` as a replacement for `fix_available`. This is to bring consistency in OCSF's boolean attributes
2. deprecating fix_available
Screenshot 2023-10-04 at 11 21 14 AM

### CODE REVIEW

**Comment by mikeradka** [comment]
I love the idea of consistency, but just want to check - do we have this documented as a strict convention, and if not, should we?

Also was curious, it looks like there are a few others which aren't prepended with `is_`

image

**Comment by floydtree** [comment]
> I love the idea of consistency, but just want to check - do we have this documented as a strict convention, and if not, should we?
> 
> Also was curious, it looks like there are a few others which aren't prepended with `is_`
> 
> image

I don't think we have strictly enforced it or have documented it yet. Probably good to do so down the road. In this PR though, just addressing the attribute in vuln object.

**Comment by floydtree** [comment]
I am creating an issue to ensure we establish a convention for all the boolean type fields. https://github.com/ocsf/ocsf-schema/issues/816

**Review by mikeradka — APPROVED** [review]
Looks good. We can tackle the convention in #816 . Thanks Rajas

**Review by awhite456 — APPROVED** [review]

**Review by Aniak5 — APPROVED** [review]
good call on this!

**Pull request merged**
