### PR TITLE
Change the version to 1.0.1-alpha

### PR DESCRIPTION
**Pull request by rroupski**

### CODE REVIEW

**Review by Aniak5 — APPROVED** [review]

**Review by floydtree — APPROVED** [review]
We should document our versioning strategy in the contribution guide.

**Comment by rroupski** [comment]
No, probably not -- our versioning strategy is commonly used on GitHub, and the readme has this line:

_Updates to OCSF follow [semantic versioning](https://semver.org/)._, which I think is good enough.

**Comment by floydtree** [comment]
> No, probably not -- our versioning strategy is commonly used on GitHub, and the readme has this line:
> 
> _Updates to OCSF follow [semantic versioning](https://semver.org/)._, which I think is good enough.

I would have agreed with you, but looking at the new PRs don't think how to update versions is fully clear yet.

**Comment by pagbabian-splunk** [comment]
What has been changed such that we are at 1.0.1-alpha?  Are the changes to the main that differ from rc.2 only description etc.?  Or did we make other changes?

**Review by pagbabian-splunk — APPROVED** [review]

**Pull request merged**
