### PR TITLE
General cleanup of metaschema

### PR DESCRIPTION
**Pull request by floydtree**
#### Description of changes:

1. Sorting all event class definition files, renaming files wherever necessary (making things consistent with class_name == file_name convention)
2. Removing includes folder to simplify reference chains in schema definition files
3. Updating vscode metadata, metaschema files
4. Updating contribution guide to remove references to includes dir

### CODE REVIEW

**Comment by rmouritzen-splunk** [comment]
If you've checked that the exported schema is the same before and after, then this is all good. (I suspect these kinds of changes should not affect the final "compiled" schema.)

**Comment by floydtree** [comment]
> If you've checked that the exported schema is the same before and after, then this is all good. (I suspect these kinds of changes should not affect the final "compiled" schema.)

Yeah, these changes do not affect the complied schema.

**Comment by mikeradka** [comment]
The meat and potatoes look good, just wanted to check, should we mention this cleanup in the 'Misc' of CHANGELOG for good measure? Once I fire up a server from my end and verify I am comfortable with approving.

**Review by rmouritzen-splunk — DISMISSED** [review]

**Review by rmouritzen-splunk — APPROVED** [review]

**Review by mikeradka — APPROVED** [review]
LGTM

**Review by jonrau-at-queryai — APPROVED** [review]
LGTM, thanks for being the janitor on this :D

**Pull request merged**
