### PR TITLE
Updating Account Change event class

### PR DESCRIPTION
**Pull request by floydtree**
Updating account_change class -
1. Description updates to account for IAM roles.
2. Adding in `http_request`, `resources`, `src_endpoint` & `identity` to allow to capture additional details (user_agent, src endpoint details, session info, mfa info of the source identity etc)

[Sample Events](https://docs.aws.amazon.com/IAM/latest/UserGuide/cloudtrail-integration.html#cloudtrail-integration-iam-api-events) that were considered for this change.

Additionally,
Updating class specific descriptions for `resources`, `src_endpoint` 

Signed-off-by: Rajas [rajaspa@amazon.com](mailto:rajaspa@amazon.com)

### CODE REVIEW

**Review by paveljos — DISMISSED** [review]

**Comment by rroupski** [comment]
Please do not merge -- it has too many changes that must be discuss first. Thanks.

**Comment by pagbabian-splunk** [comment]
Should these attributes be part of the Cloud or Cloud API profiles?  They likely will apply to account change logs coming through CloudTrail, but not via other logs like AD or even Okta.  Things like `http_request` and `src_endpoint` are related to API calls, or maybe Access Activity, so again, they can be reused as part of the profile.

**Review by jc-sumo — CHANGES_REQUESTED** [review]
Minor language change

**Review by jc-sumo — APPROVED** [review]

**Comment by floydtree** [comment]
Closing in favor of a new PR.

**Pull request closed without merging**
