### PR TITLE
Simplify environment variable object for more compact data representation; removes truncation indicator

### PR DESCRIPTION
**Pull request by antchan2**
#### Related Issue: 

Fixes [ocsf-schema#1272](https://github.com/ocsf/ocsf-schema/issues/1272)

#### Description of changes:

Simplify data representation for environment variables array by changing the type of `name` and `value` from `long_string` to `string`. This removes truncation indicators from those fields but this is a worthwhile trade-off to vastly simplify to general case since truncation is a rare occurrence. `environment_variable` remains a separate class (i.e., not reuse the `Key:Value` object) so it can be extended to more elegantly handle truncation, if there turns out to be a real need, in the future.

Screenshot 2024-12-13 at 10 34 06 AM

Screenshot 2024-12-13 at 10 33 52 AM

### CODE REVIEW

**Comment by mlmitch** [comment]
I like it

**Review by mlmitch — APPROVED** [review]

**Review by zschmerber — APPROVED** [review]
LGTM

**Review by mikeradka — APPROVED** [review]

**Comment by floydtree** [comment]
Do we wanna remove the [long_string](https://github.com/ocsf/ocsf-schema/blob/main/objects/long_string.json) object as well? We can add it down the road if needed. Or do folks see value in it? @mikeradka @zschmerber @davemcatcisco

**Comment by mikeradka** [comment]
> Do we wanna remove the [long_string](https://github.com/ocsf/ocsf-schema/blob/main/objects/long_string.json) object as well? We can add it down the road if needed. Or do folks see value in it? @mikeradka @zschmerber @davemcatcisco

Hm, good point. I am sure there could be potential down the road for this object, but as of this PR this object would be unreferenced. I suppose since this is merged now, we could either do a subsequent PR to remove this object, or keep the unreferenced object. Maybe in the spirit of keeping the schema clean, we do a follow up PR to remove the `long_string` objects. Thoughts @davemcatcisco @floydtree @zschmerber ?

**Comment by antchan2** [comment]
long_string is still used for [script content](https://github.com/ocsf/ocsf-schema/blob/171f59b08e47d50bbdc53d2ecb07f8bf756e45de/dictionary.json#L4467)

**Comment by mikeradka** [comment]
> long_string is still used for [script content](https://github.com/ocsf/ocsf-schema/blob/171f59b08e47d50bbdc53d2ecb07f8bf756e45de/dictionary.json#L4467)

Ah, good eye. I think that answers that!

**Comment by floydtree** [comment]
@antchan2 Ah, good catch! Thanks.

**Comment by davemcatcisco** [comment]
Yes, script content was the original reason for adding it, I think.

**Pull request merged**
