### PR TITLE
Update caption and desc of linux profile and extension

### PR DESCRIPTION
**Pull request by rroupski**

### CODE REVIEW

**Review by pagbabian-splunk — APPROVED** [review]

**Review by awhite456 — APPROVED** [review]

**Comment by floydtree** [comment]
Considering https://github.com/ocsf/ocsf-schema/pull/596 was merged, this PR can be closed.

**Comment by rroupski** [comment]
> Considering #596 was merged, this PR can be closed. @rroupski

This is a different PR than #596, which was to fixing the warning about missing disposition_id.

**Comment by floydtree** [comment]
> > Considering #596 was merged, this PR can be closed. @rroupski
> 
> This is a different PR than #596, which was to fixing the warning about missing disposition_id.

Right, but your commit was included in that PR, check [here](https://github.com/ocsf/ocsf-schema/pull/596/commits)

**Comment by rroupski** [comment]
> > > Considering #596 was merged, this PR can be closed. @rroupski
> > 
> > 
> > This is a different PR than #596, which was to fixing the warning about missing disposition_id.
> 
> Right, but your commit was included in that PR, check [here](https://github.com/ocsf/ocsf-schema/pull/596/commits)

OK, I see. Thanks!

**Comment by rroupski** [comment]
N/A already merged.

**Pull request closed without merging**
